import type { Flashcard, Kit, Question, QuestionCategory, Requirement } from "@/kit/schema";
import type { LlmCallLog, LlmClient } from "@/llm/gemini";
import type { CrawlResult } from "@/retrieval/crawler";
import type { DiscussionResult } from "@/retrieval/discussion";
import type { UrlPolicy } from "@/retrieval/url-guard";

export type PipelineInput = { jd: string; companyUrl: string; days: number };

export type ExtractedRole = {
  company: string | null;
  title: string;
  seniority: string;
  location: string;
  responsibilities: string[];
  requirements: Requirement[];
  /** Requirements the model proposed that the posting does not support, with why they were dropped. */
  dropped: { text: string; reason: string }[];
};

export type HiringProcess = { summary: string; stages: string[]; sources: string[] };

export type CompanyBrief = {
  summary: string;
  what_they_do: string;
  sources: string[];
  hiring_process: HiringProcess | null;
};

export type CoveragePass = { pass: number; uncovered: string[] };

/**
 * Everything the pipeline knows so far. Plain JSON on purpose: the web app
 * stores it on the job row between steps (each step is its own short request),
 * and the batch CLI simply keeps it in memory.
 */
export type PipelineState = {
  input: PipelineInput;
  research?: { crawl: CrawlResult; discussion: DiscussionResult };
  role?: ExtractedRole;
  brief?: CompanyBrief;
  /** Categories chosen from what was found, each generated by its own call. */
  plan?: QuestionCategory[];
  questions: Question[];
  flashcards: Flashcard[];
  coverage: CoveragePass[];
  kit?: Kit;
  warnings: string[];
  llmCalls: LlmCallLog[];
  nextId: { question: number; flashcard: number };
};

export type PipelineDeps = {
  llm: LlmClient;
  urlPolicy: UrlPolicy;
  now?: () => Date;
  /** Seams for tests; default to the real retrieval functions. */
  crawl?: (url: string, policy: UrlPolicy) => Promise<CrawlResult>;
  searchDiscussion?: (company: string) => Promise<DiscussionResult>;
};

export function initialState(input: PipelineInput): PipelineState {
  return { input, questions: [], flashcards: [], coverage: [], warnings: [], llmCalls: [], nextId: { question: 1, flashcard: 1 } };
}
